// AUTO-GENERATED by scripts/embed-migrations.mjs — do not edit.
// Source: drizzle/*.sql (drizzle-kit generate)

export interface EmbeddedMigration {
  id: string;
  statements: string[];
}

export const migrations: EmbeddedMigration[] = [
  {
    id: "0000_init",
    statements: [
      "CREATE TABLE `categories` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`name` text NOT NULL,\n\t`parent_id` text,\n\t`default_unit` text\n);",
      "CREATE INDEX `categories_name_idx` ON `categories` (`name`);",
      "CREATE INDEX `categories_parent_id_idx` ON `categories` (`parent_id`);",
      "CREATE INDEX `categories_updated_at_idx` ON `categories` (`updated_at`);",
      "CREATE INDEX `categories_deleted_at_idx` ON `categories` (`deleted_at`);",
      "CREATE INDEX `categories_sync_status_idx` ON `categories` (`sync_status`);",
      "CREATE TABLE `images` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`local_uri` text,\n\t`remote_object_key` text,\n\t`thumbnail_uri` text,\n\t`mime_type` text,\n\t`width` integer,\n\t`height` integer,\n\t`file_size` integer,\n\t`sha256` text,\n\t`upload_status` text NOT NULL,\n\t`captured_at` integer\n);",
      "CREATE INDEX `images_sha256_idx` ON `images` (`sha256`);",
      "CREATE INDEX `images_upload_status_idx` ON `images` (`upload_status`);",
      "CREATE INDEX `images_updated_at_idx` ON `images` (`updated_at`);",
      "CREATE INDEX `images_deleted_at_idx` ON `images` (`deleted_at`);",
      "CREATE INDEX `images_sync_status_idx` ON `images` (`sync_status`);",
      "CREATE TABLE `prices` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`product_id` text NOT NULL,\n\t`store_id` text,\n\t`currency` text NOT NULL,\n\t`regular_price_minor` integer NOT NULL,\n\t`promotional_price_minor` integer,\n\t`loyalty_price_minor` integer,\n\t`expected_checkout_price_minor` integer,\n\t`unit_price_minor` integer,\n\t`unit_price_unit` text,\n\t`min_promo_quantity` integer,\n\t`tax_included` integer,\n\t`captured_at` integer NOT NULL,\n\t`source_image_id` text,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`source_image_id`) REFERENCES `images`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `prices_product_id_idx` ON `prices` (`product_id`);",
      "CREATE INDEX `prices_store_id_idx` ON `prices` (`store_id`);",
      "CREATE INDEX `prices_captured_at_idx` ON `prices` (`captured_at`);",
      "CREATE INDEX `prices_updated_at_idx` ON `prices` (`updated_at`);",
      "CREATE INDEX `prices_deleted_at_idx` ON `prices` (`deleted_at`);",
      "CREATE INDEX `prices_sync_status_idx` ON `prices` (`sync_status`);",
      "CREATE TABLE `product_barcodes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`product_id` text NOT NULL,\n\t`barcode` text NOT NULL,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `product_barcodes_barcode_idx` ON `product_barcodes` (`barcode`);",
      "CREATE INDEX `product_barcodes_product_id_idx` ON `product_barcodes` (`product_id`);",
      "CREATE INDEX `product_barcodes_updated_at_idx` ON `product_barcodes` (`updated_at`);",
      "CREATE INDEX `product_barcodes_deleted_at_idx` ON `product_barcodes` (`deleted_at`);",
      "CREATE INDEX `product_barcodes_sync_status_idx` ON `product_barcodes` (`sync_status`);",
      "CREATE TABLE `products` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`name` text NOT NULL,\n\t`brand` text,\n\t`category_id` text,\n\t`package_quantity` integer,\n\t`package_size` text,\n\t`unit` text,\n\t`notes` text,\n\t`photo_image_id` text,\n\t`is_favorite` integer DEFAULT 0 NOT NULL,\n\t`archived_at` integer,\n\tFOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`photo_image_id`) REFERENCES `images`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `products_category_id_idx` ON `products` (`category_id`);",
      "CREATE INDEX `products_name_idx` ON `products` (`name`);",
      "CREATE INDEX `products_is_favorite_idx` ON `products` (`is_favorite`);",
      "CREATE INDEX `products_archived_at_idx` ON `products` (`archived_at`);",
      "CREATE INDEX `products_updated_at_idx` ON `products` (`updated_at`);",
      "CREATE INDEX `products_deleted_at_idx` ON `products` (`deleted_at`);",
      "CREATE INDEX `products_sync_status_idx` ON `products` (`sync_status`);",
      "CREATE TABLE `purchases` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`product_id` text NOT NULL,\n\t`trip_id` text,\n\t`store_id` text,\n\t`receipt_id` text,\n\t`receipt_line_id` text,\n\t`currency` text NOT NULL,\n\t`quantity` integer DEFAULT 1 NOT NULL,\n\t`barcode` text,\n\t`shelf_price_minor` integer NOT NULL,\n\t`unit_price_minor` integer,\n\t`expected_unit_price_minor` integer,\n\t`receipt_unit_price_minor` integer,\n\t`receipt_line_total_minor` integer,\n\t`discount_minor` integer,\n\t`final_paid_amount_minor` integer,\n\t`tax_amount_minor` integer,\n\t`price_discrepancy_minor` integer,\n\t`purchased_at` integer NOT NULL,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`trip_id`) REFERENCES `trips`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`receipt_id`) REFERENCES `receipts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`receipt_line_id`) REFERENCES `receipt_lines`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `purchases_product_id_idx` ON `purchases` (`product_id`);",
      "CREATE INDEX `purchases_trip_id_idx` ON `purchases` (`trip_id`);",
      "CREATE INDEX `purchases_store_id_idx` ON `purchases` (`store_id`);",
      "CREATE INDEX `purchases_receipt_id_idx` ON `purchases` (`receipt_id`);",
      "CREATE INDEX `purchases_purchased_at_idx` ON `purchases` (`purchased_at`);",
      "CREATE INDEX `purchases_updated_at_idx` ON `purchases` (`updated_at`);",
      "CREATE INDEX `purchases_deleted_at_idx` ON `purchases` (`deleted_at`);",
      "CREATE INDEX `purchases_sync_status_idx` ON `purchases` (`sync_status`);",
      "CREATE TABLE `receipt_lines` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`receipt_id` text NOT NULL,\n\t`product_id` text,\n\t`line_number` integer NOT NULL,\n\t`line_type` text NOT NULL,\n\t`description_raw` text,\n\t`description_corrected` text,\n\t`quantity` integer,\n\t`raw_unit_price_minor` integer,\n\t`raw_line_total_minor` integer,\n\t`unit_price_minor` integer,\n\t`line_total_minor` integer,\n\t`confidence` real,\n\t`matched_alias` text,\n\tFOREIGN KEY (`receipt_id`) REFERENCES `receipts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `receipt_lines_receipt_id_idx` ON `receipt_lines` (`receipt_id`);",
      "CREATE INDEX `receipt_lines_product_id_idx` ON `receipt_lines` (`product_id`);",
      "CREATE INDEX `receipt_lines_updated_at_idx` ON `receipt_lines` (`updated_at`);",
      "CREATE INDEX `receipt_lines_deleted_at_idx` ON `receipt_lines` (`deleted_at`);",
      "CREATE INDEX `receipt_lines_sync_status_idx` ON `receipt_lines` (`sync_status`);",
      "CREATE TABLE `receipts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`store_id` text,\n\t`trip_id` text,\n\t`currency` text NOT NULL,\n\t`subtotal_minor` integer,\n\t`total_minor` integer,\n\t`tax_minor` integer,\n\t`discount_minor` integer,\n\t`savings_minor` integer,\n\t`overcharge_minor` integer,\n\t`captured_at` integer,\n\t`source_image_id` text,\n\t`raw_ocr_text` text,\n\t`verified_at` integer,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`trip_id`) REFERENCES `trips`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`source_image_id`) REFERENCES `images`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `receipts_store_id_idx` ON `receipts` (`store_id`);",
      "CREATE INDEX `receipts_trip_id_idx` ON `receipts` (`trip_id`);",
      "CREATE INDEX `receipts_captured_at_idx` ON `receipts` (`captured_at`);",
      "CREATE INDEX `receipts_updated_at_idx` ON `receipts` (`updated_at`);",
      "CREATE INDEX `receipts_deleted_at_idx` ON `receipts` (`deleted_at`);",
      "CREATE INDEX `receipts_sync_status_idx` ON `receipts` (`sync_status`);",
      "CREATE TABLE `shopping_list_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`list_id` text NOT NULL,\n\t`product_id` text,\n\t`name` text,\n\t`quantity` integer DEFAULT 1 NOT NULL,\n\t`unit` text,\n\t`purchased` integer DEFAULT 0 NOT NULL,\n\t`store_id` text,\n\t`currency` text,\n\t`estimated_price_minor` integer,\n\tFOREIGN KEY (`list_id`) REFERENCES `shopping_lists`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `shopping_list_items_list_id_idx` ON `shopping_list_items` (`list_id`);",
      "CREATE INDEX `shopping_list_items_product_id_idx` ON `shopping_list_items` (`product_id`);",
      "CREATE INDEX `shopping_list_items_store_id_idx` ON `shopping_list_items` (`store_id`);",
      "CREATE INDEX `shopping_list_items_purchased_idx` ON `shopping_list_items` (`purchased`);",
      "CREATE INDEX `shopping_list_items_updated_at_idx` ON `shopping_list_items` (`updated_at`);",
      "CREATE INDEX `shopping_list_items_deleted_at_idx` ON `shopping_list_items` (`deleted_at`);",
      "CREATE INDEX `shopping_list_items_sync_status_idx` ON `shopping_list_items` (`sync_status`);",
      "CREATE TABLE `shopping_lists` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`name` text NOT NULL,\n\t`store_id` text,\n\t`currency` text,\n\t`estimated_total_minor` integer,\n\t`trip_id` text,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`trip_id`) REFERENCES `trips`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `shopping_lists_store_id_idx` ON `shopping_lists` (`store_id`);",
      "CREATE INDEX `shopping_lists_updated_at_idx` ON `shopping_lists` (`updated_at`);",
      "CREATE INDEX `shopping_lists_deleted_at_idx` ON `shopping_lists` (`deleted_at`);",
      "CREATE INDEX `shopping_lists_sync_status_idx` ON `shopping_lists` (`sync_status`);",
      "CREATE TABLE `stores` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`name` text NOT NULL,\n\t`branch` text,\n\t`address` text,\n\t`logo_image_id` text,\n\tFOREIGN KEY (`logo_image_id`) REFERENCES `images`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `stores_updated_at_idx` ON `stores` (`updated_at`);",
      "CREATE INDEX `stores_deleted_at_idx` ON `stores` (`deleted_at`);",
      "CREATE INDEX `stores_sync_status_idx` ON `stores` (`sync_status`);",
      "CREATE TABLE `sync_meta` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE TABLE `sync_mutations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`table_name` text NOT NULL,\n\t`record_id` text NOT NULL,\n\t`operation` text NOT NULL,\n\t`changed_fields_json` text,\n\t`payload_json` text,\n\t`device_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`local_revision` integer,\n\t`status` text NOT NULL,\n\t`last_attempt_at` integer,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`error` text\n);",
      "CREATE INDEX `sync_mutations_status_idx` ON `sync_mutations` (`status`);",
      "CREATE INDEX `sync_mutations_table_name_idx` ON `sync_mutations` (`table_name`);",
      "CREATE INDEX `sync_mutations_record_id_idx` ON `sync_mutations` (`record_id`);",
      "CREATE INDEX `sync_mutations_created_at_idx` ON `sync_mutations` (`created_at`);",
      "CREATE TABLE `trips` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`device_id` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`sync_status` text NOT NULL,\n\t`field_versions_json` text,\n\t`store_id` text,\n\t`status` text NOT NULL,\n\t`started_at` integer NOT NULL,\n\t`ended_at` integer,\n\t`currency` text,\n\t`budget_minor` integer,\n\t`notes` text,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `trips_store_id_idx` ON `trips` (`store_id`);",
      "CREATE INDEX `trips_status_idx` ON `trips` (`status`);",
      "CREATE INDEX `trips_started_at_idx` ON `trips` (`started_at`);",
      "CREATE INDEX `trips_updated_at_idx` ON `trips` (`updated_at`);",
      "CREATE INDEX `trips_deleted_at_idx` ON `trips` (`deleted_at`);",
      "CREATE INDEX `trips_sync_status_idx` ON `trips` (`sync_status`);"
    ]
  },
  {
    id: "0001_ocr_price_columns",
    statements: [
      "ALTER TABLE `prices` ADD `ocr_raw_text` text;",
      "ALTER TABLE `prices` ADD `ocr_confidence` real;"
    ]
  },
  {
    id: "0002_sync_conflicts",
    statements: [
      "CREATE TABLE `sync_conflicts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`table_name` text NOT NULL,\n\t`record_id` text NOT NULL,\n\t`field` text NOT NULL,\n\t`winning_side` text NOT NULL,\n\t`winning_value_json` text,\n\t`losing_value_json` text,\n\t`local_revision` integer,\n\t`remote_revision` integer,\n\t`local_device_id` text,\n\t`remote_device_id` text\n);",
      "CREATE INDEX `sync_conflicts_record_idx` ON `sync_conflicts` (`table_name`,`record_id`);",
      "CREATE INDEX `sync_conflicts_created_idx` ON `sync_conflicts` (`created_at`);"
    ]
  }
];
