/**
 * Idempotent DDL for the canonical sync schema.
 *
 * The synced-table definitions mirror `mobile/drizzle/0000_init.sql` exactly
 * (same columns, types, and indexes) plus the server-only `server_seq` column
 * + index per table and the server-only tables. `IF NOT EXISTS` makes this
 * safe to run on every boot; a future drizzle-kit setup can replace it
 * without changing the wire behavior.
 */
import type { ApiDb } from "./client.js";

const STATEMENTS: readonly string[] = [
  // -- canonical synced tables (server_seq added) ---------------------------
  `CREATE TABLE IF NOT EXISTS categories (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    name text NOT NULL,
    parent_id text,
    default_unit text
  )`,
  `CREATE INDEX IF NOT EXISTS categories_name_idx ON categories (name)`,
  `CREATE INDEX IF NOT EXISTS categories_parent_id_idx ON categories (parent_id)`,
  `CREATE INDEX IF NOT EXISTS categories_updated_at_idx ON categories (updated_at)`,
  `CREATE INDEX IF NOT EXISTS categories_deleted_at_idx ON categories (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS categories_sync_status_idx ON categories (sync_status)`,
  `CREATE INDEX IF NOT EXISTS categories_server_seq_idx ON categories (server_seq)`,

  `CREATE TABLE IF NOT EXISTS images (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    local_uri text,
    remote_object_key text,
    thumbnail_uri text,
    mime_type text,
    width integer,
    height integer,
    file_size integer,
    sha256 text,
    upload_status text NOT NULL,
    captured_at integer
  )`,
  `CREATE INDEX IF NOT EXISTS images_sha256_idx ON images (sha256)`,
  `CREATE INDEX IF NOT EXISTS images_upload_status_idx ON images (upload_status)`,
  `CREATE INDEX IF NOT EXISTS images_updated_at_idx ON images (updated_at)`,
  `CREATE INDEX IF NOT EXISTS images_deleted_at_idx ON images (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS images_sync_status_idx ON images (sync_status)`,
  `CREATE INDEX IF NOT EXISTS images_server_seq_idx ON images (server_seq)`,

  `CREATE TABLE IF NOT EXISTS stores (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    name text NOT NULL,
    branch text,
    address text,
    logo_image_id text
  )`,
  `CREATE INDEX IF NOT EXISTS stores_updated_at_idx ON stores (updated_at)`,
  `CREATE INDEX IF NOT EXISTS stores_deleted_at_idx ON stores (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS stores_sync_status_idx ON stores (sync_status)`,
  `CREATE INDEX IF NOT EXISTS stores_server_seq_idx ON stores (server_seq)`,

  `CREATE TABLE IF NOT EXISTS products (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    name text NOT NULL,
    brand text,
    category_id text,
    package_quantity integer,
    package_size text,
    unit text,
    notes text,
    photo_image_id text,
    is_favorite integer DEFAULT 0 NOT NULL,
    archived_at integer
  )`,
  `CREATE INDEX IF NOT EXISTS products_category_id_idx ON products (category_id)`,
  `CREATE INDEX IF NOT EXISTS products_name_idx ON products (name)`,
  `CREATE INDEX IF NOT EXISTS products_is_favorite_idx ON products (is_favorite)`,
  `CREATE INDEX IF NOT EXISTS products_archived_at_idx ON products (archived_at)`,
  `CREATE INDEX IF NOT EXISTS products_updated_at_idx ON products (updated_at)`,
  `CREATE INDEX IF NOT EXISTS products_deleted_at_idx ON products (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS products_sync_status_idx ON products (sync_status)`,
  `CREATE INDEX IF NOT EXISTS products_server_seq_idx ON products (server_seq)`,

  `CREATE TABLE IF NOT EXISTS product_barcodes (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    product_id text NOT NULL,
    barcode text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_barcode_idx ON product_barcodes (barcode)`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_product_id_idx ON product_barcodes (product_id)`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_updated_at_idx ON product_barcodes (updated_at)`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_deleted_at_idx ON product_barcodes (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_sync_status_idx ON product_barcodes (sync_status)`,
  `CREATE INDEX IF NOT EXISTS product_barcodes_server_seq_idx ON product_barcodes (server_seq)`,

  `CREATE TABLE IF NOT EXISTS prices (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    product_id text NOT NULL,
    store_id text,
    currency text NOT NULL,
    regular_price_minor integer NOT NULL,
    promotional_price_minor integer,
    loyalty_price_minor integer,
    expected_checkout_price_minor integer,
    unit_price_minor integer,
    unit_price_unit text,
    min_promo_quantity integer,
    tax_included integer,
    captured_at integer NOT NULL,
    source_image_id text,
    ocr_raw_text text,
    ocr_confidence real
  )`,
  `CREATE INDEX IF NOT EXISTS prices_product_id_idx ON prices (product_id)`,
  `CREATE INDEX IF NOT EXISTS prices_store_id_idx ON prices (store_id)`,
  `CREATE INDEX IF NOT EXISTS prices_captured_at_idx ON prices (captured_at)`,
  `CREATE INDEX IF NOT EXISTS prices_updated_at_idx ON prices (updated_at)`,
  `CREATE INDEX IF NOT EXISTS prices_deleted_at_idx ON prices (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS prices_sync_status_idx ON prices (sync_status)`,
  `CREATE INDEX IF NOT EXISTS prices_server_seq_idx ON prices (server_seq)`,

  `CREATE TABLE IF NOT EXISTS trips (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    store_id text,
    status text NOT NULL,
    started_at integer NOT NULL,
    ended_at integer,
    currency text,
    budget_minor integer,
    notes text
  )`,
  `CREATE INDEX IF NOT EXISTS trips_store_id_idx ON trips (store_id)`,
  `CREATE INDEX IF NOT EXISTS trips_status_idx ON trips (status)`,
  `CREATE INDEX IF NOT EXISTS trips_started_at_idx ON trips (started_at)`,
  `CREATE INDEX IF NOT EXISTS trips_updated_at_idx ON trips (updated_at)`,
  `CREATE INDEX IF NOT EXISTS trips_deleted_at_idx ON trips (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS trips_sync_status_idx ON trips (sync_status)`,
  `CREATE INDEX IF NOT EXISTS trips_server_seq_idx ON trips (server_seq)`,

  `CREATE TABLE IF NOT EXISTS receipts (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    store_id text,
    trip_id text,
    currency text NOT NULL,
    subtotal_minor integer,
    total_minor integer,
    tax_minor integer,
    discount_minor integer,
    savings_minor integer,
    overcharge_minor integer,
    captured_at integer,
    source_image_id text,
    raw_ocr_text text,
    verified_at integer
  )`,
  `CREATE INDEX IF NOT EXISTS receipts_store_id_idx ON receipts (store_id)`,
  `CREATE INDEX IF NOT EXISTS receipts_trip_id_idx ON receipts (trip_id)`,
  `CREATE INDEX IF NOT EXISTS receipts_captured_at_idx ON receipts (captured_at)`,
  `CREATE INDEX IF NOT EXISTS receipts_updated_at_idx ON receipts (updated_at)`,
  `CREATE INDEX IF NOT EXISTS receipts_deleted_at_idx ON receipts (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS receipts_sync_status_idx ON receipts (sync_status)`,
  `CREATE INDEX IF NOT EXISTS receipts_server_seq_idx ON receipts (server_seq)`,

  `CREATE TABLE IF NOT EXISTS receipt_lines (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    receipt_id text NOT NULL,
    product_id text,
    line_number integer NOT NULL,
    line_type text NOT NULL,
    description_raw text,
    description_corrected text,
    quantity integer,
    raw_unit_price_minor integer,
    raw_line_total_minor integer,
    unit_price_minor integer,
    line_total_minor integer,
    confidence real,
    matched_alias text
  )`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_receipt_id_idx ON receipt_lines (receipt_id)`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_product_id_idx ON receipt_lines (product_id)`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_updated_at_idx ON receipt_lines (updated_at)`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_deleted_at_idx ON receipt_lines (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_sync_status_idx ON receipt_lines (sync_status)`,
  `CREATE INDEX IF NOT EXISTS receipt_lines_server_seq_idx ON receipt_lines (server_seq)`,

  `CREATE TABLE IF NOT EXISTS purchases (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    product_id text NOT NULL,
    trip_id text,
    store_id text,
    receipt_id text,
    receipt_line_id text,
    currency text NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    barcode text,
    shelf_price_minor integer NOT NULL,
    unit_price_minor integer,
    expected_unit_price_minor integer,
    receipt_unit_price_minor integer,
    receipt_line_total_minor integer,
    discount_minor integer,
    final_paid_amount_minor integer,
    tax_amount_minor integer,
    price_discrepancy_minor integer,
    purchased_at integer NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS purchases_product_id_idx ON purchases (product_id)`,
  `CREATE INDEX IF NOT EXISTS purchases_trip_id_idx ON purchases (trip_id)`,
  `CREATE INDEX IF NOT EXISTS purchases_store_id_idx ON purchases (store_id)`,
  `CREATE INDEX IF NOT EXISTS purchases_receipt_id_idx ON purchases (receipt_id)`,
  `CREATE INDEX IF NOT EXISTS purchases_purchased_at_idx ON purchases (purchased_at)`,
  `CREATE INDEX IF NOT EXISTS purchases_updated_at_idx ON purchases (updated_at)`,
  `CREATE INDEX IF NOT EXISTS purchases_deleted_at_idx ON purchases (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS purchases_sync_status_idx ON purchases (sync_status)`,
  `CREATE INDEX IF NOT EXISTS purchases_server_seq_idx ON purchases (server_seq)`,

  `CREATE TABLE IF NOT EXISTS shopping_lists (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    name text NOT NULL,
    store_id text,
    currency text,
    estimated_total_minor integer,
    trip_id text
  )`,
  `CREATE INDEX IF NOT EXISTS shopping_lists_store_id_idx ON shopping_lists (store_id)`,
  `CREATE INDEX IF NOT EXISTS shopping_lists_updated_at_idx ON shopping_lists (updated_at)`,
  `CREATE INDEX IF NOT EXISTS shopping_lists_deleted_at_idx ON shopping_lists (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS shopping_lists_sync_status_idx ON shopping_lists (sync_status)`,
  `CREATE INDEX IF NOT EXISTS shopping_lists_server_seq_idx ON shopping_lists (server_seq)`,

  `CREATE TABLE IF NOT EXISTS shopping_list_items (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    deleted_at integer,
    device_id text NOT NULL,
    revision integer DEFAULT 0 NOT NULL,
    sync_status text NOT NULL,
    field_versions_json text,
    server_seq integer,
    list_id text NOT NULL,
    product_id text,
    name text,
    quantity integer DEFAULT 1 NOT NULL,
    unit text,
    purchased integer DEFAULT 0 NOT NULL,
    store_id text,
    currency text,
    estimated_price_minor integer
  )`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_list_id_idx ON shopping_list_items (list_id)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_product_id_idx ON shopping_list_items (product_id)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_store_id_idx ON shopping_list_items (store_id)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_purchased_idx ON shopping_list_items (purchased)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_updated_at_idx ON shopping_list_items (updated_at)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_deleted_at_idx ON shopping_list_items (deleted_at)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_sync_status_idx ON shopping_list_items (sync_status)`,
  `CREATE INDEX IF NOT EXISTS shopping_list_items_server_seq_idx ON shopping_list_items (server_seq)`,

  // -- server-only tables ---------------------------------------------------
  `CREATE TABLE IF NOT EXISTS sync_meta (
    key text PRIMARY KEY NOT NULL,
    value text,
    updated_at integer NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS sync_mutations_applied (
    mutation_id text PRIMARY KEY NOT NULL,
    device_id text NOT NULL,
    table_name text NOT NULL,
    record_id text NOT NULL,
    operation text NOT NULL,
    accepted integer NOT NULL,
    revision integer NOT NULL,
    updated_at integer NOT NULL,
    error text,
    applied_at integer NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS sync_mutations_applied_device_idx ON sync_mutations_applied (device_id, applied_at)`,

  `CREATE TABLE IF NOT EXISTS sync_conflicts (
    id text PRIMARY KEY NOT NULL,
    created_at integer NOT NULL,
    table_name text NOT NULL,
    record_id text NOT NULL,
    field text NOT NULL,
    winning_side text NOT NULL,
    winning_value_json text,
    losing_value_json text,
    local_revision integer,
    remote_revision integer,
    local_device_id text,
    remote_device_id text
  )`,
  `CREATE INDEX IF NOT EXISTS sync_conflicts_record_idx ON sync_conflicts (table_name, record_id)`,
  `CREATE INDEX IF NOT EXISTS sync_conflicts_created_idx ON sync_conflicts (created_at)`,
];

/** Runs every DDL statement once (IF NOT EXISTS keeps it idempotent) and seeds counters. */
export function migrate(db: ApiDb, nowMs: number = Date.now()): void {
  for (const statement of STATEMENTS) {
    db.sqlite.exec(statement);
  }
  db.sqlite
    .prepare(
      `INSERT INTO sync_meta (key, value, updated_at) VALUES ('server_seq', '0', ?)
       ON CONFLICT(key) DO NOTHING`,
    )
    .run(nowMs);
}
